name: unsplash
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.3

  built_value: ^6.7.1
  built_collection: ^4.2.2
  http: ^0.12.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  built_value_generator: ^6.7.1
  mockito: ^4.1.1
  test: ^1.6.0
  test_coverage: ^0.3.0

flutter:
  uses-material-design: true